version: "3.9"

services:
  python:
    platform: linux/amd64
    container_name: python-qiskit
    image: qiskit-jupyter:latest
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c "jupyter notebook --port=8888 --no-browser --ip=0.0.0.0 --allow-root --NotebookApp.token=abcd"
    volumes:
      - ./python/src:/code
    ports:
      - 8888:8888
